Repository scuffed56/SCUFFED5.0, pull requests merged in 2023-01, with the labels that each got.

#1 Minor fixes for form nations
  common/decisions/formNation.txt
Labels: bug

#5 TCDTF Womens auxilary
  common/ideas/_role_of_women.txt
Labels: Balance Change

#7 TCDTF Italy Fix
  common/ideas/italy.txt
  common/national_focus/italy.txt
Labels: bug, Balance Change

#6 TCDTF Host Tool
  common/game_rules/00_game_rules.txt
  common/on_actions/hosttool_on_actions.txt
  common/scripted_guis/hosttool.txt
  interface/hosttool.gui
  localisation/english/horsttool_l_english.yml
Labels: Feature

#10 TCDTF Dockyard Button
  common/game_rules/00_game_rules.txt
  common/scripted_diplomatic_actions/send_dockyard.txt
  localisation/english/replace/r56_game_rules_l_english.yml
  localisation/english/send_dockyard_l_english.yml
Labels: Feature, QOL

#2 TCDTF Focus Fixes and Balancing
  common/decisions/formable_nation_decisions.txt
  common/ideas/egypt.txt
  common/ideas/portugal.txt
  common/national_focus/FrenchIndochina.txt
  common/national_focus/colombia.txt
  common/national_focus/congo.txt
  common/national_focus/egypt.txt
  common/national_focus/malaysia.txt
  common/national_focus/philippines.txt
  common/national_focus/portugal.txt
  common/national_focus/r56_gran_colombia_shared.txt
  common/national_focus/r56_greece.txt
  common/national_focus/saudi_arabia.txt
Labels: Balance Change

#13 Fullchord changes
  common/buildings/00_buildings.txt
  common/game_rules/00_game_rules.txt
  common/ideas/r56i_laws_leadership.txt
  common/ideas/r56i_laws_social.txt
  common/scripted_diplomatic_actions/pay_civ_factory.txt
  localisation/english/replace/r56_game_rules_l_english.yml
Labels: bug, Balance Change
